# Sound Device Options mod definition file
modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/ichttt/sounddeviceoptions/issues"
displayURL="https://minecraft.curseforge.com/projects/more-sound-config"
license="GPL v3"
# logoFile="firstaid_logo.png"
authors="ichttt"
[[mods]]
    modId="sounddeviceoptions"
    version="${file.jarVersion}"
    displayName="Sound Device Options"
    description="Sound Device Options allows you to change the sound device while the game is running"
#[[dependencies.sounddeviceoptions]]
#    modId="forge"
#    mandatory=true
#    versionRange="[28.0.0,)"
#    ordering="NONE"
#    side="BOTH"
[[dependencies.sounddeviceoptions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"